# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

CCACHE=/usr/bin/ccache
GC=/usr/bin/go
AS=/usr/bin/gcc
CXX=/usr/bin/g++
CC=/usr/bin/gcc
MM=/usr/bin/gcc
MXX=/usr/bin/g++
ZC=/usr/bin/zig
CS=/usr/bin/dotnet
CU=/usr/bin/clang
RC=/usr/bin/rustc

GCAR=/usr/bin/go
ZCAR=/usr/bin/zig
AR=/usr/bin/ar
RCAR=/usr/bin/rustc
ZCSH=/usr/bin/zig
SH=/usr/bin/g++
CS=/usr/bin/dotnet
RCSH=/usr/bin/rustc
GCLD=/usr/bin/go
ZCLD=/usr/bin/zig
LD=/usr/bin/g++
RCLD=/usr/bin/rustc

input_LD=/usr/bin/g++
input_CXX=/usr/bin/g++
input_CXX=/usr/bin/g++
input_CXX=/usr/bin/g++
dotty_LD=/usr/bin/g++
dotty_CXX=/usr/bin/g++
dotty_CXX=/usr/bin/g++
dotty_CXX=/usr/bin/g++
core_AR=/usr/bin/ar
core_CXX=/usr/bin/g++
core_CXX=/usr/bin/g++
core_CXX=/usr/bin/g++

input_CXXFLAGS=-O0 -std=c++23 -I build/.objs/input/linux/x86_64/debug/include/cxx -include common.hpp -Iinclude -Icore/include -Ivendor -Ideps
input_CXXFLAGS=-O0 -std=c++23 -I build/.objs/input/linux/x86_64/debug/include/cxx -include common.hpp -Iinclude -Icore/include -Ivendor -Ideps
input_CXXFLAGS=-O0 -std=c++23 -I build/.objs/input/linux/x86_64/debug/include/cxx -include common.hpp -Iinclude -Icore/include -Ivendor -Ideps
input_LDFLAGS=
dotty_CXXFLAGS=-O0 -std=c++23 -I build/.objs/dotty/linux/x86_64/debug/include/cxx -include common.hpp -Iinclude -Icore/include -Ivendor -Ideps
dotty_CXXFLAGS=-O0 -std=c++23 -I build/.objs/dotty/linux/x86_64/debug/include/cxx -include common.hpp -Iinclude -Icore/include -Ivendor -Ideps
dotty_CXXFLAGS=-O0 -std=c++23 -I build/.objs/dotty/linux/x86_64/debug/include/cxx -include common.hpp -Iinclude -Icore/include -Ivendor -Ideps
dotty_LDFLAGS=-Lbuild/linux/x86_64/debug -lcore
core_CXXFLAGS=-O0 -std=c++23 -I build/.objs/core/linux/x86_64/debug/include/cxx -include common.hpp -Iinclude -Icore/include -Ivendor -Ideps
core_CXXFLAGS=-O0 -std=c++23 -I build/.objs/core/linux/x86_64/debug/include/cxx -include common.hpp -Iinclude -Icore/include -Ivendor -Ideps
core_CXXFLAGS=-O0 -std=c++23 -I build/.objs/core/linux/x86_64/debug/include/cxx -include common.hpp -Iinclude -Icore/include -Ivendor -Ideps
core_ARFLAGS=-cr

default:  input dotty core script

all:  input dotty core script

.PHONY: default all  input dotty core script

input: build/linux/x86_64/debug/input
build/linux/x86_64/debug/input: build/.objs/input/linux/x86_64/debug/tests/input.cpp.o
	@echo linking.debug input
	@mkdir -p build/linux/x86_64/debug
	$(VV)$(input_LDFLAGS)$(input_LD) -o build/linux/x86_64/debug/input build/.objs/input/linux/x86_64/debug/tests/input.cpp.o

build/.objs/input/linux/x86_64/debug/tests/input.cpp.o: tests/input.cpp
	@echo ccache compiling.debug tests/input.cpp
	@mkdir -p build/.objs/input/linux/x86_64/debug/tests
	$(VV)$(input_CXX) -c $(input_CXXFLAGS) -o build/.objs/input/linux/x86_64/debug/tests/input.cpp.o tests/input.cpp

dotty: build/linux/x86_64/debug/dotty
build/linux/x86_64/debug/dotty: build/linux/x86_64/debug/libcore.a build/.objs/dotty/linux/x86_64/debug/src/cli.cpp.o build/.objs/dotty/linux/x86_64/debug/src/cli_commands.cpp.o build/.objs/dotty/linux/x86_64/debug/src/main.cpp.o
	@echo linking.debug dotty
	@mkdir -p build/linux/x86_64/debug
	$(VV)$(dotty_LD) -o build/linux/x86_64/debug/dotty build/.objs/dotty/linux/x86_64/debug/src/cli.cpp.o build/.objs/dotty/linux/x86_64/debug/src/cli_commands.cpp.o build/.objs/dotty/linux/x86_64/debug/src/main.cpp.o $(dotty_LDFLAGS)

build/.objs/dotty/linux/x86_64/debug/src/cli.cpp.o: src/cli.cpp
	@echo ccache compiling.debug src/cli.cpp
	@mkdir -p build/.objs/dotty/linux/x86_64/debug/src
	$(VV)$(dotty_CXX) -c $(dotty_CXXFLAGS) -o build/.objs/dotty/linux/x86_64/debug/src/cli.cpp.o src/cli.cpp

build/.objs/dotty/linux/x86_64/debug/src/cli_commands.cpp.o: src/cli_commands.cpp
	@echo ccache compiling.debug src/cli_commands.cpp
	@mkdir -p build/.objs/dotty/linux/x86_64/debug/src
	$(VV)$(dotty_CXX) -c $(dotty_CXXFLAGS) -o build/.objs/dotty/linux/x86_64/debug/src/cli_commands.cpp.o src/cli_commands.cpp

build/.objs/dotty/linux/x86_64/debug/src/main.cpp.o: src/main.cpp
	@echo ccache compiling.debug src/main.cpp
	@mkdir -p build/.objs/dotty/linux/x86_64/debug/src
	$(VV)$(dotty_CXX) -c $(dotty_CXXFLAGS) -o build/.objs/dotty/linux/x86_64/debug/src/main.cpp.o src/main.cpp

core: build/linux/x86_64/debug/libcore.a
build/linux/x86_64/debug/libcore.a: script build/.objs/core/linux/x86_64/debug/core/src/cfman.cpp.o build/.objs/core/linux/x86_64/debug/core/src/config_parser.cpp.o build/.objs/core/linux/x86_64/debug/core/src/master_cfg_parser.cpp.o build/.objs/core/linux/x86_64/debug/core/src/profile.cpp.o
	@echo linking.debug libcore.a
	@mkdir -p build/linux/x86_64/debug
	$(VV)$(core_AR) $(core_ARFLAGS) build/linux/x86_64/debug/libcore.a build/.objs/core/linux/x86_64/debug/core/src/cfman.cpp.o build/.objs/core/linux/x86_64/debug/core/src/config_parser.cpp.o build/.objs/core/linux/x86_64/debug/core/src/master_cfg_parser.cpp.o build/.objs/core/linux/x86_64/debug/core/src/profile.cpp.o

build/.objs/core/linux/x86_64/debug/core/src/cfman.cpp.o: core/src/cfman.cpp
	@echo ccache compiling.debug core/src/cfman.cpp
	@mkdir -p build/.objs/core/linux/x86_64/debug/core/src
	$(VV)$(core_CXX) -c $(core_CXXFLAGS) -o build/.objs/core/linux/x86_64/debug/core/src/cfman.cpp.o core/src/cfman.cpp

build/.objs/core/linux/x86_64/debug/core/src/config_parser.cpp.o: core/src/config_parser.cpp
	@echo ccache compiling.debug core/src/config_parser.cpp
	@mkdir -p build/.objs/core/linux/x86_64/debug/core/src
	$(VV)$(core_CXX) -c $(core_CXXFLAGS) -o build/.objs/core/linux/x86_64/debug/core/src/config_parser.cpp.o core/src/config_parser.cpp

build/.objs/core/linux/x86_64/debug/core/src/master_cfg_parser.cpp.o: core/src/master_cfg_parser.cpp
	@echo ccache compiling.debug core/src/master_cfg_parser.cpp
	@mkdir -p build/.objs/core/linux/x86_64/debug/core/src
	$(VV)$(core_CXX) -c $(core_CXXFLAGS) -o build/.objs/core/linux/x86_64/debug/core/src/master_cfg_parser.cpp.o core/src/master_cfg_parser.cpp

build/.objs/core/linux/x86_64/debug/core/src/profile.cpp.o: core/src/profile.cpp
	@echo ccache compiling.debug core/src/profile.cpp
	@mkdir -p build/.objs/core/linux/x86_64/debug/core/src
	$(VV)$(core_CXX) -c $(core_CXXFLAGS) -o build/.objs/core/linux/x86_64/debug/core/src/profile.cpp.o core/src/profile.cpp

script:
clean:  clean_input clean_dotty clean_core clean_script

clean_input: 
	@rm -rf build/linux/x86_64/debug/input
	@rm -rf build/linux/x86_64/debug/input.sym
	@rm -rf build/.objs/input/linux/x86_64/debug/tests/input.cpp.o

clean_dotty:  clean_core
	@rm -rf build/linux/x86_64/debug/dotty
	@rm -rf build/linux/x86_64/debug/dotty.sym
	@rm -rf build/.objs/dotty/linux/x86_64/debug/src/cli.cpp.o
	@rm -rf build/.objs/dotty/linux/x86_64/debug/src/cli_commands.cpp.o
	@rm -rf build/.objs/dotty/linux/x86_64/debug/src/main.cpp.o

clean_core:  clean_script
	@rm -rf build/linux/x86_64/debug/libcore.a
	@rm -rf build/linux/x86_64/debug/core.sym
	@rm -rf build/.objs/core/linux/x86_64/debug/core/src/cfman.cpp.o
	@rm -rf build/.objs/core/linux/x86_64/debug/core/src/config_parser.cpp.o
	@rm -rf build/.objs/core/linux/x86_64/debug/core/src/master_cfg_parser.cpp.o
	@rm -rf build/.objs/core/linux/x86_64/debug/core/src/profile.cpp.o

clean_script: 

